<?php

namespace Deployer;

use Deployer\Payload\Payload;

/**
 * Test class for Deployer.
 * Generated by PHPUnit on 2012-09-10 at 04:24:50.
 */
class DeployerTest extends \PHPUnit_Framework_TestCase {
    
    /**
     * The mock object of Deployer
     * @var PHPUnit_Framework_MockObject_MockObject|Deployer
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $payload = $this->getMockForAbstractClass('\Deployer\Payload\Payload', array(array()));
        $this->object = $this->getMockForAbstractClass('\Deployer\Deployer', array($payload));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Deployer\Deployer::options
     */
    public function testOptions() {
        $this->object->options(array('logFile' => false, 'branch' => 'test', 'blah' => null));
        $property = new \ReflectionProperty(get_class($this->object), 'options');
        $property->setAccessible(true);
        $options = $property->getValue($this->object);
        $this->assertCount(8, $options);
        $this->assertEquals(false, $options['logFile']);
        $this->assertEquals(true, $options['lastLogFile']);
        $this->assertEquals('test', $options['branch']);
    }

    /**
     * @covers Deployer\Deployer::login
     */
    public function testLogin() {
        $usernameProp = new \ReflectionProperty(get_class($this->object), 'username');
        $usernameProp->setAccessible(true);
        $passwordProp = new \ReflectionProperty(get_class($this->object), 'password');
        $passwordProp->setAccessible(true);
        $this->assertEquals(null, $usernameProp->getValue($this->object));
        $this->assertEquals(null, $passwordProp->getValue($this->object));
        
        $this->object->login('user', 'password');
        $this->assertEquals('user', $usernameProp->getValue($this->object));
        $this->assertEquals('password', $passwordProp->getValue($this->object));
    }

    /**
     * @covers Deployer\Deployer::log
     */
    public function testLog() {
        $this->assertTrue(method_exists($this->object, 'log'));
    }

    /**
     * @covers Deployer\Deployer::execute
     */
    public function testExecute() {
        $this->assertTrue(method_exists($this->object, 'execute'));
    }

    /**
     * @covers Deployer\Deployer::deploy
     */
    public function testDeploy() {
        $this->assertTrue(method_exists($this->object, 'deploy'));
    }

}
