<?php
namespace Deployer\Drivers\Github;

/**
 * Test class for Deployer.
 * Generated by PHPUnit on 2012-09-09 at 07:43:57.
 */
class DeployerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Deployer\Drivers\Github::validate
     */
    public function testValidateSuccess()
    {
        $source = json_decode(file_get_contents('test/sampleGoodGithubData.json'), true);
        $object = new Deployer(new Payload($source), array('logFile' => null));
        $this->assertEquals('https://github.com/defunkt/github.git', $object->buildUrl());
    }
}
