<?php

namespace Deployer\Drivers\Github;

/**
 * Test class for Deployer.
 * Generated by PHPUnit on 2012-09-09 at 07:43:57.
 */
class DeployerTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Deployer\Drivers\Github::validate
     */
    public function testValidateSuccess() {
        $source = json_decode(file_get_contents('test/sampleGoodGithubData.json'), true);
        $object = new Deployer(new Payload($source), array('logFile' => null));
        $this->assertEquals('https://github.com/defunkt/github.git', $object->buildUrl());
    }

}
