<?php

namespace Deployer\Drivers\BitBucket;

/**
 * Test class for Deployer.
 * Generated by PHPUnit on 2012-09-09 at 07:30:31.
 */
class DeployerTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Deployer\Drivers\BitBucket::validate
     */
    public function testValidateFail() {
        $source = json_decode(file_get_contents('test/sampleGoodGithubData.json'), true);
        $object = new Deployer($source, array('logFile' => null));
        $this->setExpectedException('ErrorException');
        $object->validate();
    }

}