<?php
namespace Deployer\Drivers\BitBucket;

/**
 * Test class for Deployer.
 * Generated by PHPUnit on 2012-09-09 at 07:30:31.
 */
class DeployerTest extends \PHPUnit_Framework_TestCase
{
    public function testValidateFail()
    {
        $source = json_decode(file_get_contents('test/sampleGoodGithubData.json'), true);
        $object = new Deployer(new Payload($source), array('logFile' => null));
    }
}
